### ISSUE TITLE
Crash due to filling up input queue

### ISSUE THREAD

**Issue by AaronM04** [conwayste/conwayste#15]
Bug report from a loyal user. JK, I'm a developer...

It turns out we _can_ hit this condition:

```rust
    /// Adds an event to the queue.
    /// This will panic if we fill up the queue past `NUM_OF_QUEUED_INPUTS`.
    pub fn add(&mut self, input: InputAction) {
        // Curious to see if we actually can hit this condition
        if self.events.len() >= NUM_OF_QUEUED_INPUTS {
            println!("{:?}", self.events);
            assert!(false);
        }

        self.events.push_back(input);
    }
```

I think it happens when the system is heavily loaded.

Backtrace:
```
[MouseMovement(178, 210), MouseMovement(391, 123), MouseMovement(592, 57), MouseMovement(718, 27), MouseMovement(782, 27), MouseMovement(811, 38), MouseMovement(823, 55), MouseMovement(823, 78), MouseMovement(818, 104), MouseMovement(806, 130)]
thread 'main' panicked at 'assertion failed: false', src/input.rs:67:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
             at libstd/panicking.rs:410
   6: client::input::InputManager::add
             at src/input.rs:67
   7: <client::MainState as ggez::event::EventHandler>::mouse_motion_event
             at src/client.rs:0
   8: ggez::event::run
             at /home/[censored]/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/event.rs:252
   9: client::main
             at src/client.rs:1137
  10: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

*Version*: commit 78932bc2aa85654e4b7eb44481d5654d790423f0
*Platform*: x86_64 Linux, Fedora 29

**Comment by Manghi** [comment]
Fixed in the ui_widgets branch, #53
