### ISSUE TITLE
Initializing with server_mode(false) crashes conwayste

### ISSUE THREAD

**Issue by Manghi** [conwayste/conwayste#48]
I don't think we've ever tested with `server_mode(false)` aka `is_server = false`. 

The panic happens during the first cell toggle within Conwayste's `init_patterns(...)` because the `known` BitGrid isn't set up properly (blocked during `BigBang::new()` by requiring `is_server` flag to be true).

This probably has more changes than a simple `remove is_server` associated with it.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AccessDenied { reason: "not a known cell for player 0: col=100, row=70" }', 

** OMITTED **

   9: client::MainState::new
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:798
             at conwayste/src/client.rs:535
  10: client::main
             at conwayste/src/client.rs:1277
  11: std::rt::lang_start::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start

```

**Comment by Manghi** [comment]
To be addressed when we implement client-side multiplayer.
